const CART_LIST_REQUEST = "CART_LIST_REQUEST";
const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
const CART_LIST_FAIL = "CART_LIST_FAIL";
const CART_ADD_ITEM = "CART_ADD_ITEM";

export { CART_LIST_REQUEST, CART_LIST_SUCCESS, CART_LIST_FAIL, CART_ADD_ITEM };
