const CART_LIST_REQUEST = "CART_LIST_REQUEST";
const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
const CART_LIST_FAIL = "CART_LIST_FAIL";
const CART_ADD_REQUEST = "CART_ADD_REQUEST";
const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
const CART_ADD_FAIL = "CART_ADD_FAIL";

export {
  CART_LIST_REQUEST,
  CART_LIST_SUCCESS,
  CART_LIST_FAIL,
  CART_ADD_REQUEST,
  CART_ADD_SUCCESS,
  CART_ADD_FAIL,
};
